enum EnvKey {
  PORT = 'PORT',
  BASE_PATH = 'BASE_PATH',
  CORS_WHITE_LIST = 'CORS_WHITE_LIST',
  MAX_REQUEST_SIZE = 'MAX_REQUEST_SIZE',

  // JWT
  ACCESS_TOKEN_KEY = 'ACCESS_TOKEN_KEY',
  ACCESS_TOKEN_EXPIRED_IN = 'ACCESS_TOKEN_EXPIRED_IN',
  REFRESH_TOKEN_KEY = 'REFRESH_TOKEN_KEY',
  REFRESH_TOKEN_EXPIRED_IN = 'REFRESH_TOKEN_EXPIRED_IN',
  // Super admin
  SUPER_ADMIN_ACCOUNT = 'SUPER_ADMIN_ACCOUNT',
  SUPER_ADMIN_PASSWORD = 'SUPER_ADMIN_PASSWORD',
  // Swagger
  SWAGGER_PATH = 'SWAGGER_PATH',
}

export default EnvKey;
